apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: peb302rqq-python
  janus-idp.io/tekton: peb302rqq-python
  backstage.io/kubernetes-id: peb302rqq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: peb302rqq-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
