apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: peb302rqq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: peb302rqq-python 
  name: peb302rqq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: peb302rqq-python 
